reload:
  description: Reload all generic_thermostat_plus entities.
set_preset_temp:
  name: Set preset modes temperature
  description: Sets the temperature for the preset modes.
  target:
    entity:
      integration: generic_thermostat_plus
      domain: climate
  fields:
    away_temp:
      name: Away
      description: Away mode temperature
      required: false
      advanced: false
      example: 14.0
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    eco_temp:
      name: Eco
      description: Eco mode temperature
      required: false
      advanced: false
      example: 17.5
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    boost_temp:
      name: Boost
      description: Boost mode temperature
      required: false
      advanced: false
      example: 22.0
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    comfort_temp:
      name: Comfort
      description: Comfort mode temperature
      required: false
      advanced: false
      example: 21.0
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    home_temp:
      name: Home
      description: Home mode temperature
      required: false
      advanced: false
      example: 19.0
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    sleep_temp:
      name: Sleep
      description: Sleep mode temperature
      required: false
      advanced: false
      example: 18.5
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
    activity_temp:
      name: Activity
      description: Activity mode temperature
      required: false
      advanced: false
      example: 20.0
      selector:
        number:
          min: 0
          max: 95
          step: 0.1
          mode: slider
